### PR TITLE
get endpoint path variables

### PR DESCRIPTION
**Pull request by sunb26**
Done exams and moving to TO ready to get back on the grind :)

### CODE REVIEW

**Comment by sunb26** [comment]
I was having issues with running cmd/serve because I think renovate had made updates to pnpm-lock such that bazel was not supporting it anymore:

image

I tried running bazel cmds to update the file:

e.g
bazel run -- @pnpm//:pnpm --dir $PWD install --lockfile-only

but nothing seemed to work. I also changed the lockfile version manually in the file but then I started getting errors with the packages in the file saying I needed to include name and version fields for every single one of them.

My fix for this was re-generating the file from scratch. Now there are conflicts and from a quick glance it's because I am downgrading many of the versions. Wanted to get a second opinion before I just accept the older versions.

**Comment by sunb26** [comment]
added gorilla/mux dependency. Since we include variables in the URL path - gorilla mux provides a way to easily access the path variables without having to regex. The regular net/http library does not have support for this. Gorilla mux is also compatible with most types from the net/http library making the interaction between the two pretty easy.

**Comment by Lev1ty** [comment]
> I was having issues with running cmd/serve because I think renovate had made updates to pnpm-lock such that bazel was not supporting it anymore:
> 
> image
> 
> I tried running bazel cmds to update the file:
> 
> e.g bazel run -- @pnpm//:pnpm --dir $PWD install --lockfile-only
> 
> but nothing seemed to work. I also changed the lockfile version manually in the file but then I started getting errors with the packages in the file saying I needed to include name and version fields for every single one of them.
> 
> My fix for this was re-generating the file from scratch. Now there are conflicts and from a quick glance it's because I am downgrading many of the versions. Wanted to get a second opinion before I just accept the older versions.

i have also been experiencing this. seems to be because renovate is using a newer version of pnpm, which supports a newer version of pnpm lockfile. in the meantime, i'm also doing what you're doing, havnig to either run `pnpm i --lockfile-only` or deleting the lockfile and regenerating. as long as the versions in the lockfile comply with the package files we're good

**Comment by Lev1ty** [comment]
> added gorilla/mux dependency. Since we include variables in the URL path - gorilla mux provides a way to easily access the path variables without having to regex. The regular net/http library does not have support for this. Gorilla mux is also compatible with most types from the net/http library making the interaction between the two pretty easy.

does the newer `net/http` package satisfy requirements? see 

```go
"mux.HandleFunc("GET /orders/{id}", func(w http.ResponseWriter, r *http.Request) {
    id := r.PathValue("id")
    fmt.Fprintf(w, "Get order with id: %s", id)
})"

// https://douglasmakey.medium.com/go-1-22s-http-package-updates-42aca70ceb9b#:~:text=mux.HandleFunc(%22GET%20%2Forders%2F%7Bid%7D%22%2C%20func(w%20http.ResponseWriter%2C%20r,order%20with%20id%3A%20%25s%22%2C%20id)%0A%7D)
```

**Comment by sunb26** [comment]
> > added gorilla/mux dependency. Since we include variables in the URL path - gorilla mux provides a way to easily access the path variables without having to regex. The regular net/http library does not have support for this. Gorilla mux is also compatible with most types from the net/http library making the interaction between the two pretty easy.
> 
> does the newer `net/http` package satisfy requirements? see
> 
> ```go
> "mux.HandleFunc("GET /orders/{id}", func(w http.ResponseWriter, r *http.Request) {
>     id := r.PathValue("id")
>     fmt.Fprintf(w, "Get order with id: %s", id)
> })"
> 
> // https://douglasmakey.medium.com/go-1-22s-http-package-updates-42aca70ceb9b#:~:text=mux.HandleFunc(%22GET%20%2Forders%2F%7Bid%7D%22%2C%20func(w%20http.ResponseWriter%2C%20r,order%20with%20id%3A%20%25s%22%2C%20id)%0A%7D)
> ```

Ahh cool I see this was pretty recent. Must have missed it thanks!

**Comment by sunb26** [comment]
> > I was having issues with running cmd/serve because I think renovate had made updates to pnpm-lock such that bazel was not supporting it anymore:
> > image
> > I tried running bazel cmds to update the file:
> > e.g bazel run -- @pnpm//:pnpm --dir $PWD install --lockfile-only
> > but nothing seemed to work. I also changed the lockfile version manually in the file but then I started getting errors with the packages in the file saying I needed to include name and version fields for every single one of them.
> > My fix for this was re-generating the file from scratch. Now there are conflicts and from a quick glance it's because I am downgrading many of the versions. Wanted to get a second opinion before I just accept the older versions.
> 
> i have also been experiencing this. seems to be because renovate is using a newer version of pnpm, which supports a newer version of pnpm lockfile. in the meantime, i'm also doing what you're doing, havnig to either run `pnpm i --lockfile-only` or deleting the lockfile and regenerating. as long as the versions in the lockfile comply with the package files we're good. see [aspect-build/rules_js#1652](https://github.com/aspect-build/rules_js/issues/1652)

Unlucky :(

**Review by Lev1ty — CHANGES_REQUESTED** [review]
https://github.com/sunb26/xat/actions/runs/8961663429/job/24609514293#step:6:876

**Review by Lev1ty — APPROVED** [review]

**Review by Zack-Ren — APPROVED** [review]

**Comment by Zack-Ren** [comment]
lets goooooo

**Pull request merged**
